### PR TITLE
config command_start

### PR DESCRIPTION
**Pull request by ReimuYk**
change command_start to '#'

### CODE REVIEW

**Comment by laazy** [comment]
you need to rebase first. main has changed.

**Review by laazy — CHANGES_REQUESTED** [review]
rebase first

**Comment by laazy** [comment]
I have rebased from main. So I will approve this pr.

**Review by laazy — APPROVED** [review]

**Comment by Veiasai** [comment]
could you guys maintain a changelog?

docs/changelog.md

```
# FundBot
## 1.0.1
* xxxx
## 1.0.0
```

**Pull request merged**
